version: '3.7'

services:
  fms-reporter:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip3 install -r requirements.txt && python3 main.py"
    environment:
      - API_KEY=${API_KEY}
      - TEAM_ID=${TEAM_ID}
      - LOG_LEVEL=${LOG_LEVEL}
      - PYTHONUNBUFFERED=1
    restart: "no"