name: FindMyShift Reporter CI

on:
  # push:
  #   branches: ["main"]
  # Run every Tuesday at 8:00 AM
  schedule:
    - cron: "0 8 * * 2"

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "settings.json"
          json: ${{ secrets.SETTINGS_JSON }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run FindMyShift Reporter
        run: |
          python3 main.py --slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
          API_KEY: ${{ secrets.API_KEY }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          DAYS_TO_FETCH: ${{ vars.DAYS_TO_FETCH }}